project_id = "betukaetgtzkfhxhwqma"

[functions.agent-chat]
verify_jwt = false

[functions.image-edit]
verify_jwt = false

[functions.image-generate]
verify_jwt = false

[functions.pet-identify]
verify_jwt = false

[functions.story-caption]
verify_jwt = false
